on:
  push:
    tags:
      - "v*"
name: Release
jobs:
  ci:
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.x]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Setup Poetry
        uses: abatilo/actions-poetry@v2.0.0
      - name: Build wheel
        run: poetry build
      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: dist/spotcli-*.whl
